"""One-off script: fetch CVM company registry and build config/cnpj_map.yaml."""

import re
from io import StringIO
from pathlib import Path

import requests
import pandas as pd
import yaml

CAD_URL = "https://dados.cvm.gov.br/dados/CIA_ABERTA/CAD/DADOS/cad_cia_aberta.csv"
COVERAGE_YAML = Path("config/coverage.yaml")
OUTPUT_YAML = Path("config/cnpj_map.yaml")


def _normalize(s: str) -> str:
    return re.sub(r'\s+', ' ', str(s).upper().strip())


def main():
    print("Fetching CVM company registry...")
    resp = requests.get(CAD_URL, timeout=60)
    resp.raise_for_status()
    cad = pd.read_csv(
        StringIO(resp.content.decode("latin-1")),
        sep=";",
        dtype=str,
        usecols=lambda c: c in ("CNPJ_CIA", "DENOM_SOCIAL", "DENOM_COMERC", "SIT"),
    )
    cad = cad[cad["SIT"].str.strip() == "ATIVO"].copy()
    cad["_name"] = cad["DENOM_SOCIAL"].fillna("").apply(_normalize)

    with open(COVERAGE_YAML) as f:
        coverage = yaml.safe_load(f)

    ticker_map: dict = coverage.get("ticker_map", {})
    result: dict[str, str] = {}
    missing: list[str] = []

    for ticker, substring in ticker_map.items():
        needle = _normalize(substring)
        matches = cad[cad["_name"].str.contains(needle, regex=False)]
        if matches.empty:
            print(f"  WARNING: no match for {ticker} ({substring!r})")
            missing.append(ticker)
            continue
        row = matches.loc[matches["_name"].str.len().idxmin()]
        cnpj_raw = str(row["CNPJ_CIA"]).strip()
        digits = re.sub(r"\D", "", cnpj_raw)
        if len(digits) == 14:
            cnpj_fmt = f"{digits[:2]}.{digits[2:5]}.{digits[5:8]}/{digits[8:12]}-{digits[12:]}"
        else:
            cnpj_fmt = cnpj_raw
        result[ticker] = cnpj_fmt
        print(f"  {ticker}: {cnpj_fmt}  ({row['_name']})")

    lines = [
        "# Auto-generated by scripts/build_cnpj_map.py — review before committing\n",
        "tickers:\n",
    ]
    for ticker, cnpj in result.items():
        lines.append(f'  {ticker}: "{cnpj}"\n')
    if missing:
        lines.append("\n# Could not match (populate manually):\n")
        for t in missing:
            lines.append(f'#  {t}: ""\n')

    OUTPUT_YAML.parent.mkdir(exist_ok=True)
    OUTPUT_YAML.write_text("".join(lines), encoding="utf-8")
    print(f"\nWrote {OUTPUT_YAML} with {len(result)} entries ({len(missing)} missing).")


if __name__ == "__main__":
    main()
